spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.37.160.246:3306/mybatisdemo?useSSL=false
    username: admin
    password: 123456
server:
  port: 8082

mybatis:
  # MyBatis全局配置文件路径
  config-location: classpath:mybatis-config.xml
  mapper-locations:
## 控制台日志输出记录，开发调试使用
#logging:
#  level:
#    com.wasteland.blogsourcecode.mybatisdemo.mapper:
#      debug
